version: '3.7'
services:
  server:
    build: .
    volumes:
      - .:/src
    working_dir: /src
    command: python app.py
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:10.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
